name: Bug report
description: Something in netwp does not work as documented.
labels: ["type: fix", "semver: patch"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: What you ran, what you expected, and what you got instead.
      placeholder: |
        I ran `...`
        I expected ...
        Instead ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `netwp version`.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - Linux
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output or logs
      render: shell
